import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";
import { GlobalContextProvider } from "@/context/store";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-zinc-50">
                <GlobalContextProvider>
                    <Navbar />
                    <main>{children}</main>
                    <Footer />
                    <Toaster richColors position="top-center" />
                </GlobalContextProvider>
            </body>
        </html>
    );
}
